spring:
  application:
    name: API GAEWAY
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
           - Path=/employee/**
        filters:
          - name: CircuitBreaker
            args:
             name: Employee-Service
             fallbackuri: forward:/employeeServiceFallback
      - id: ADDRESS-SERVICE
        uri: lb://ADDRESS-SERVICE
        predicates:
           - Path=/address/**
        filters:
           - name: CircuitBreaker
             args:
               name: Address-Service
               fallbackuri: forward:/addressServiceFallback
               
hystrix:
   command:
      execution:
        isolation:
          thread:
             timeoutInMiliseconds: 5000
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix-stream
        

          